[build]
  publish = "dist"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Configure secrets scanning to ignore known safe environment variables
[build.environment]
  NODE_VERSION = "18"
  # Omit legitimate environment variables from secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_STRIPE_PUBLISHABLE_KEY,VITE_SUPABASE_URL,VITE_STRIPE_SCHOLAR_MONTHLY_PRICE_ID,VITE_STRIPE_SCHOLAR_ANNUAL_PRICE_ID,VITE_STRIPE_PROFESSIONAL_MONTHLY_PRICE_ID,VITE_STRIPE_PROFESSIONAL_ANNUAL_PRICE_ID,VITE_STRIPE_INSTITUTION_MONTHLY_PRICE_ID,VITE_STRIPE_INSTITUTION_ANNUAL_PRICE_ID"
  # All sensitive keys should be set in Netlify UI under Site Settings > Environment Variables

# Development settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  functions = "netlify/functions"
