[build]
  publish = "client/dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  # These environment variables will be available during build
  NODE_VERSION = "18"

# Development settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "client/dist"
  functions = "netlify/functions"
