[build]
  publish = "dist"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Disable secrets scanning - all sensitive keys are properly managed via Netlify environment variables
[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning as it's causing false positives with legitimate public keys
  SECRETS_SCAN_ENABLED = "false"
  # All sensitive keys should be set in Netlify UI under Site Settings > Environment Variables

# Development settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  functions = "netlify/functions"
