[build]
  publish = "client/dist"
  command = "cd client && npm install && npm run build"
  base = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Development settings
[dev]
  command = "cd client && npm run dev"
  port = 5173
  publish = "client/dist"
  functions = "netlify/functions"
