[build]
  publish = "dist"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # OPENAI_API_KEY should be set in Netlify UI under Site Settings > Environment Variables

# Development settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  functions = "netlify/functions"
